### ISSUE TITLE
Нельзя создать смену сразу с текущим и поздним обедом

### ISSUE THREAD

**Issue by vikonikus** [Olga-koml/kinosmena#23]
ОР: Можно создать смену с текущим и поздним обедом.
ФР: Нельзя создать смену с текущим и поздним обедом. Ошибка 400.

curl --location 'http://rbychin.ddns.net:6080/api/shifts/?tid=12345' \
--header 'Content-Type: application/json' \
--data '{
  "project": 8,
  "start_date": "2024-03-30T12:50:01Z",
  "end_date": "2024-03-31T08:50:01Z",
  "is_current_lunch": true,
  "is_late_lunch": true,
  "is_per_diem": true,
  "is_day_off": true,
  "is_coefficient_shift": true,
  "services_sum": 123456
}'

**Comment by Olga-koml** [comment]
исправлено

https://github.com/Olga-koml/kinosmena/pull/29/files#diff-4c86cd5574917d8e9e6c285c0c702731826a122da6c506d3461e56fb25339ad9

**Comment by Olga-koml** [comment]
сделано
